stages:
  - validation
  - submission

validate:
  stage: validation
  script: curl -s https://courses.cs.washington.edu/courses/cse331/19wi/gitlab/validate.sh | bash

submission-hw4:
  stage: submission
  script: curl -s https://courses.cs.washington.edu/courses/cse331/19wi/gitlab/checktag.sh | bash -s hw4-final
  allow_failure: true

submission-hw5-part1:
  stage: submission
  script: curl -s https://courses.cs.washington.edu/courses/cse331/19wi/gitlab/checktag.sh | bash -s hw5-part1-final
  allow_failure: true

submission-hw5:
  stage: submission
  script: curl -s https://courses.cs.washington.edu/courses/cse331/19wi/gitlab/checktag.sh | bash -s hw5-final
  allow_failure: true