stages:
  - validation
  - submission

validate:
  stage: validation
  script: curl -s https://courses.cs.washington.edu/courses/cse331/19wi/gitlab/validate.sh | bash

submission-hw5:
  stage: submission
  script: curl -s https://courses.cs.washington.edu/courses/cse331/19wi/gitlab/checktag.sh | bash -s hw5-final
  allow_failure: true

submission-hw6:
  stage: submission
  script: curl -s https://courses.cs.washington.edu/courses/cse331/19wi/gitlab/checktag.sh | bash -s hw6-final
  allow_failure: true

submission-hw7:
  stage: submission
  script: curl -s https://courses.cs.washington.edu/courses/cse331/19wi/gitlab/checktag.sh | bash -s hw7-final
  allow_failure: true